### ISSUE TITLE
Run queue listing

### ISSUE THREAD

**Issue by ml4** [straubt1/tfx#12]
## Expected Behavior

NA

## Actual Behavior

Tabulate which workspaces by name are running and which workspaces are _queued due to limited concurrency_.

**Comment by straubt1** [comment]
This should now be possible with the following command:
`tfx workspace list --run-status plan_queued`

If you wanted just a count -> `tfx workspace list --run-status plan_queued -j | jq '. | length'`

**Comment by ml4** [comment]
Beautiful Tom, that's the ticket.
