### ISSUE TITLE
update install guide to call out GO version, and update to go 1.9 

### ISSUE THREAD

**Issue by abuxton** [straubt1/tfx#27]
## Expected Behavior
Go released 1.19 02-aug-22, as such it is now creeping into default images
currently tfx is 1.18. 
Readme should call out expected go version
probably should update and test against 1.19  https://go.dev/doc/go1.19 (only one small language declaration change)

## Actual Behavior

fails to install and panics on 1.19 and 1.17 (does explain version issue in error panic, but it is wordy)

## Steps to Reproduce the Problem

  1. run install on 1.19 based environment

## Specifications

**tfx version:**
latest

**Comment by straubt1** [comment]
Upgrade in flight.

The docs do call out the supported version of Go: https://github.com/straubt1/tfx/blob/4c55aac94f03e3f717b29176f6a5773e7027e377/site/docs/index.md?plain=1#L35
