### ISSUE TITLE
Feature Request: Filter workspaces by VCS repository name

### ISSUE THREAD

**Issue by rhughes1** [straubt1/tfx#31]
## Problem Statement

As a user searching for workspaces, I should be able to query for workspaces based on the name of the repository. This way I can see common repositories and where they are used.

It could be added in as a flag as part of the `workspace list` command like this: `tfx workspace list --search-repository ORG/REPOSITORY_NAME` 

## Specifications

**tfx version:** 0.1.0
**Terraform Cloud or Terraform Enterprise:** Terraform Cloud
**Terraform Enterprise Version:** N/A
**Terraform Code Version:** 1.2.4

**Comment by straubt1** [comment]
Great idea!

Took the opportunity to refactor the filter setup as I a expect other filter options being needed in the future.

Example:
```
$ tfx workspace list --repository straubt1/tfe-workspace-seed                         
Using config file: /Users/tstraub/.tfx.hcl
List Workspaces for Organization: firefly
Found 1 Filtered Workspaces
╭────────────────────┬─────────────────────┬───────────────────────┬───────────┬─────────────────────────────┬────────╮
│ NAME               │ ID                  │ CURRENT RUN CREATED   │ STATUS    │ REPOSITORY                  │ LOCKED │
├────────────────────┼─────────────────────┼───────────────────────┼───────────┼─────────────────────────────┼────────┤
│ tfe-workspace-seed │ ws-DqAFf9SzVkM9dyai │ Wed Jul 21 01:09 2021 │ discarded │ straubt1/tfe-workspace-seed │ true   │
╰────────────────────┴─────────────────────┴───────────────────────┴───────────┴─────────────────────────────┴────────╯
```

This filter can also be used in conjuction with the `--search` and `--run-status` filters to stack conditions. In other words, give me all Workspaces with a repository identifier that are also in the "error" run status.
`tfx workspace list --repository straubt1/demo --run-status errored`.
