### ISSUE TITLE
Global configuration from environment variables

### ISSUE THREAD

**Issue by grahame-murray-db** [straubt1/tfx#7]
# Feature Request
Currently tfx only supports CLI flags or an HCL file for setting global configuration values.  It would be useful, especially in pipelines, to be able to inject these values at the environment level.

I suggest `TFE_TOKEN` and `TFE_HOSTNAME`, which are inline with the [tfe provider](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs).  `TFE_ORGANIZATION` seems like an obvious extension.

**Comment by straubt1** [comment]
Great idea!

**Comment by straubt1** [comment]
Any flag can be set via an environment variable with a key the same as the flag, but all caps.

Example 'tfeToken' can be set with 'TFETOKEN'.

To add consistency like you mention with the TFE provider, aliases have been added for token, hostname, and organization as you suggested.

Thank you for the feedback!
