### ISSUE TITLE
Update to latest go version

### ISSUE THREAD

**Issue by kokosnuss** [straubt1/tfx#89]
Hey @straubt1 ,

we are currently using your tfx to publish private providers in our TFE registries. Thanks for your effort so far.
Are you still developing tfx or is there no further development planned?

Maybe you could update to the latest go version to fix some CVES
## Expected Behavior
Build tfx with go 1.21.3

## Actual Behavior
tfx is build with go 1.19

## Steps to Reproduce the Problem

  1. Change go version in go.mod to go 1.21
  2. make update
  3. make build
 

## Specifications

**tfx version:**
**Terraform Cloud or Terraform Enterprise: enterprise
*

**Comment by straubt1** [comment]
@kokosnuss Thank you for the inquiry and apologies on the delay.
New release should go out soon to fix a few bugs and update Go and it's packages.

Development is still planned for the future!
Any interesting features, feel free to add a Github issue.
